server:
  port: 8081

spring:
  datasource:
  username: root
  password: Abcde@2021
  url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
#    连接池名
    pool-name: DateHikariCP
    minimum-idle: 5
    idle-timeout: 18000
    maximum-pool-size: 10
    auto-commit: true
    max-lifetime: 18000
    connection-timeout: 3000
    connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.server.pojo
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.example.server.mapper: debug